<?xml version="1.0"?>

<!--
verbs-fr.xml - List of French verbs with their conjugation template
Copyright (C) 2003-2010 Pierre Sarrazin <http://sarrazip.com/>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
02110-1301, USA.
-->

<!DOCTYPE verbs-fr [
<!ELEMENT verbs-fr (v+)>
<!ELEMENT v (i, t, aspirate-h?)>
<!ELEMENT i (#PCDATA)>  <!-- infinitive -->
<!ELEMENT t (#PCDATA)><!-- template (radical:termination) -->
<!ELEMENT aspirate-h EMPTY>  <!-- useful for verbs starting with h -->
]>

<!--
The <v> lines are sorted with this filter:
env LANG=en_US.utf8 sort -f
-->

<verbs-fr>

	 <v><i>abandonner</i><t>aim:er</t></v>
	 <v><i>abattre</i><t>bat:tre</t></v>
	 <v><i>aborder</i><t>aim:er</t></v>
	 <v><i>accepter</i><t>aim:er</t></v>
	 <v><i>accomplir</i><t>fin:ir</t></v>
	 <v><i>accorder</i><t>aim:er</t></v>
	 <v><i>accrocher</i><t>aim:er</t></v>
	 <v><i>accueillir</i><t>cueill:ir</t></v>
	 <v><i>accuser</i><t>aim:er</t></v>
	 <v><i>acheter</i><t>ach:eter</t></v>
	 <v><i>achever</i><t>l:ever</t></v>
	 <v><i>admettre</i><t>m:ettre</t></v>
	 <v><i>adresser</i><t>aim:er</t></v>
	 <v><i>affirmer</i><t>aim:er</t></v>
	 <v><i>agir</i><t>fin:ir</t></v>
	 <v><i>agiter</i><t>aim:er</t></v>
	 <v><i>aider</i><t>aim:er</t></v>
	 <v><i>aimer</i><t>aim:er</t></v>
	 <v><i>ajouter</i><t>aim:er</t></v>
	 <v><i>aller</i><t>:aller</t></v>
	 <v><i>allumer</i><t>aim:er</t></v>
	 <v><i>amener</i><t>m:ener</t></v>
	 <v><i>amuser</i><t>aim:er</t></v>
	 <v><i>animer</i><t>aim:er</t></v>
	 <v><i>annoncer</i><t>pla:cer</t></v>
	 <v><i>apercevoir</i><t>dé:cevoir</t></v>
	 <v><i>apparaître</i><t>rep:aître</t></v>
	 <v><i>appartenir</i><t>t:enir</t></v>
	 <v><i>appeler</i><t>app:eler</t></v>
	 <v><i>apporter</i><t>aim:er</t></v>
	 <v><i>apprendre</i><t>pr:endre</t></v>
	 <v><i>approcher</i><t>aim:er</t></v>
	 <v><i>approuver</i><t>aim:er</t></v>
	 <v><i>appuyer</i><t>netto:yer</t></v>
	 <v><i>armer</i><t>aim:er</t></v>
	 <v><i>arracher</i><t>aim:er</t></v>
	 <v><i>arrêter</i><t>aim:er</t></v>
	 <v><i>arriver</i><t>aim:er</t></v>
	 <v><i>asseoir</i><t>ass:eoir</t></v>
	 <v><i>assister</i><t>aim:er</t></v>
	 <v><i>assurer</i><t>aim:er</t></v>
	 <v><i>attacher</i><t>aim:er</t></v>
	 <v><i>attaquer</i><t>aim:er</t></v>
	 <v><i>atteindre</i><t>crai:ndre</t></v>
	 <v><i>attendre</i><t>ten:dre</t></v>
	 <v><i>attirer</i><t>aim:er</t></v>
	 <v><i>avancer</i><t>pla:cer</t></v>
	 <v><i>avoir</i><t>:avoir</t></v>
	 <v><i>avouer</i><t>aim:er</t></v>
	 <v><i>baisser</i><t>aim:er</t></v>
	 <v><i>battre</i><t>bat:tre</t></v>
	 <v><i>boire</i><t>b:oire</t></v>
	 <v><i>briller</i><t>aim:er</t></v>
	 <v><i>briser</i><t>aim:er</t></v>
	 <v><i>brûler</i><t>aim:er</t></v>
	 <v><i>cacher</i><t>aim:er</t></v>
	 <v><i>calmer</i><t>aim:er</t></v>
	 <v><i>caresser</i><t>aim:er</t></v>
	 <v><i>casser</i><t>aim:er</t></v>
	 <v><i>causer</i><t>aim:er</t></v>
	 <v><i>céder</i><t>c:éder</t></v>
	 <v><i>cesser</i><t>aim:er</t></v>
	 <v><i>changer</i><t>man:ger</t></v>
	 <v><i>chanter</i><t>aim:er</t></v>
	 <v><i>charger</i><t>man:ger</t></v>
	 <v><i>chasser</i><t>aim:er</t></v>
	 <v><i>chercher</i><t>aim:er</t></v>
	 <v><i>choisir</i><t>fin:ir</t></v>
	 <v><i>commander</i><t>aim:er</t></v>
	 <v><i>commencer</i><t>pla:cer</t></v>
	 <v><i>composer</i><t>aim:er</t></v>
	 <v><i>comprendre</i><t>pr:endre</t></v>
	 <v><i>compter</i><t>aim:er</t></v>
	 <v><i>conclure</i><t>concl:ure</t></v>
	 <v><i>condamner</i><t>aim:er</t></v>
	 <v><i>conduire</i><t>condui:re</t></v>
	 <v><i>confier</i><t>aim:er</t></v>
	 <v><i>confondre</i><t>ten:dre</t></v>
	 <v><i>connaître</i><t>rep:aître</t></v>
	 <v><i>consentir</i><t>men:tir</t></v>
	 <v><i>considérer</i><t>réf:érer</t></v>
	 <v><i>construire</i><t>condui:re</t></v>
	 <v><i>consulter</i><t>aim:er</t></v>
	 <v><i>contenir</i><t>t:enir</t></v>
	 <v><i>contenter</i><t>aim:er</t></v>
	 <v><i>continuer</i><t>aim:er</t></v>
	 <v><i>convenir</i><t>t:enir</t></v>
	 <v><i>coucher</i><t>aim:er</t></v>
	 <v><i>couler</i><t>aim:er</t></v>
	 <v><i>couper</i><t>aim:er</t></v>
	 <v><i>courir</i><t>cour:ir</t></v>
	 <v><i>coûter</i><t>aim:er</t></v>
	 <v><i>couvrir</i><t>ouv:rir</t></v>
	 <v><i>craindre</i><t>crai:ndre</t></v>
	 <v><i>créer</i><t>aim:er</t></v>
	 <v><i>creuser</i><t>aim:er</t></v>
	 <v><i>crier</i><t>aim:er</t></v>
	 <v><i>croire</i><t>cr:oire</t></v>
	 <v><i>croiser</i><t>aim:er</t></v>
	 <v><i>danser</i><t>aim:er</t></v>
	 <v><i>déchirer</i><t>aim:er</t></v>
	 <v><i>décider</i><t>aim:er</t></v>
	 <v><i>déclarer</i><t>aim:er</t></v>
	 <v><i>découvrir</i><t>ouv:rir</t></v>
	 <v><i>décrire</i><t>écri:re</t></v>
	 <v><i>défendre</i><t>ten:dre</t></v>
	 <v><i>dégager</i><t>man:ger</t></v>
	 <v><i>demander</i><t>aim:er</t></v>
	 <v><i>demeurer</i><t>aim:er</t></v>
	 <v><i>dépasser</i><t>aim:er</t></v>
	 <v><i>déposer</i><t>aim:er</t></v>
	 <v><i>descendre</i><t>ten:dre</t></v>
	 <v><i>désigner</i><t>aim:er</t></v>
	 <v><i>désirer</i><t>aim:er</t></v>
	 <v><i>dessiner</i><t>aim:er</t></v>
	 <v><i>détacher</i><t>aim:er</t></v>
	 <v><i>détourner</i><t>aim:er</t></v>
	 <v><i>détruire</i><t>condui:re</t></v>
	 <v><i>devenir</i><t>t:enir</t></v>
	 <v><i>deviner</i><t>aim:er</t></v>
	 <v><i>devoir</i><t>d:evoir</t></v>
	 <v><i>dire</i><t>d:ire</t></v>
	 <v><i>diriger</i><t>man:ger</t></v>
	 <v><i>discuter</i><t>aim:er</t></v>
	 <v><i>disparaître</i><t>rep:aître</t></v>
	 <v><i>disposer</i><t>aim:er</t></v>
	 <v><i>distinguer</i><t>aim:er</t></v>
	 <v><i>dominer</i><t>aim:er</t></v>
	 <v><i>donner</i><t>aim:er</t></v>
	 <v><i>dormir</i><t>dor:mir</t></v>
	 <v><i>douter</i><t>aim:er</t></v>
	 <v><i>dresser</i><t>aim:er</t></v>
	 <v><i>durer</i><t>aim:er</t></v>
	 <v><i>écarter</i><t>aim:er</t></v>
	 <v><i>échapper</i><t>aim:er</t></v>
	 <v><i>éclairer</i><t>aim:er</t></v>
	 <v><i>éclater</i><t>aim:er</t></v>
	 <v><i>écouter</i><t>aim:er</t></v>
	 <v><i>écraser</i><t>aim:er</t></v>
	 <v><i>écrire</i><t>écri:re</t></v>
	 <v><i>effacer</i><t>pla:cer</t></v>
	 <v><i>élever</i><t>l:ever</t></v>
	 <v><i>éloigner</i><t>aim:er</t></v>
	 <v><i>embrasser</i><t>aim:er</t></v>
	 <v><i>emmener</i><t>m:ener</t></v>
	 <v><i>emparer</i><t>aim:er</t></v>
	 <v><i>empêcher</i><t>aim:er</t></v>
	 <v><i>employer</i><t>netto:yer</t></v>
	 <v><i>emporter</i><t>aim:er</t></v>
	 <v><i>endormir</i><t>dor:mir</t></v>
	 <v><i>enfermer</i><t>aim:er</t></v>
	 <v><i>enfoncer</i><t>pla:cer</t></v>
	 <v><i>engager</i><t>man:ger</t></v>
	 <v><i>enlever</i><t>l:ever</t></v>
	 <v><i>entendre</i><t>ten:dre</t></v>
	 <v><i>entourer</i><t>aim:er</t></v>
	 <v><i>entraîner</i><t>aim:er</t></v>
	 <v><i>entrer</i><t>aim:er</t></v>
	 <v><i>entretenir</i><t>t:enir</t></v>
	 <v><i>envelopper</i><t>aim:er</t></v>
	 <v><i>envoyer</i><t>env:oyer</t></v>
	 <v><i>éprouver</i><t>aim:er</t></v>
	 <v><i>espérer</i><t>réf:érer</t></v>
	 <v><i>essayer</i><t>pa:yer</t></v>
	 <v><i>essuyer</i><t>netto:yer</t></v>
	 <v><i>établir</i><t>fin:ir</t></v>
	 <v><i>étaler</i><t>aim:er</t></v>
	 <v><i>éteindre</i><t>crai:ndre</t></v>
	 <v><i>étendre</i><t>ten:dre</t></v>
	 <v><i>étonner</i><t>aim:er</t></v>
	 <v><i>étouffer</i><t>aim:er</t></v>
	 <v><i>être</i><t>:être</t></v>
	 <v><i>étudier</i><t>aim:er</t></v>
	 <v><i>éviter</i><t>aim:er</t></v>
	 <v><i>examiner</i><t>aim:er</t></v>
	 <v><i>exécuter</i><t>aim:er</t></v>
	 <v><i>exiger</i><t>man:ger</t></v>
	 <v><i>exister</i><t>aim:er</t></v>
	 <v><i>expliquer</i><t>aim:er</t></v>
	 <v><i>exposer</i><t>aim:er</t></v>
	 <v><i>exprimer</i><t>aim:er</t></v>
	 <v><i>faire</i><t>f:aire</t></v>
	 <v><i>falloir</i><t>fa:lloir</t></v>
	 <v><i>fatiguer</i><t>aim:er</t></v>
	 <v><i>fermer</i><t>aim:er</t></v>
	 <v><i>figurer</i><t>aim:er</t></v>
	 <v><i>finir</i><t>fin:ir</t></v>
	 <v><i>fixer</i><t>aim:er</t></v>
	 <v><i>fonder</i><t>aim:er</t></v>
	 <v><i>forcer</i><t>pla:cer</t></v>
	 <v><i>former</i><t>aim:er</t></v>
	 <v><i>franchir</i><t>fin:ir</t></v>
	 <v><i>frapper</i><t>aim:er</t></v>
	 <v><i>fuir</i><t>fu:ir</t></v>
	 <v><i>fumer</i><t>aim:er</t></v>
	 <v><i>gagner</i><t>aim:er</t></v>
	 <v><i>garder</i><t>aim:er</t></v>
	 <v><i>glisser</i><t>aim:er</t></v>
	 <v><i>grandir</i><t>fin:ir</t></v>
	 <v><i>guider</i><t>aim:er</t></v>
	 <v><i>habiller</i><t>aim:er</t></v>
	 <v><i>habiter</i><t>aim:er</t></v>
	 <v><i>habituer</i><t>aim:er</t></v>
	 <v><i>haïr</i><t>ha:ïr</t></v>
	 <v><i>hésiter</i><t>aim:er</t></v>
	 <v><i>heurter</i><t>aim:er</t></v>
	 <v><i>ignorer</i><t>aim:er</t></v>
	 <v><i>imaginer</i><t>aim:er</t></v>
	 <v><i>importer</i><t>aim:er</t></v>
	 <v><i>imposer</i><t>aim:er</t></v>
	 <v><i>indiquer</i><t>aim:er</t></v>
	 <v><i>inquiéter</i><t>décr:éter</t></v>
	 <v><i>inspirer</i><t>aim:er</t></v>
	 <v><i>installer</i><t>aim:er</t></v>
	 <v><i>intéresser</i><t>aim:er</t></v>
	 <v><i>interroger</i><t>man:ger</t></v>
	 <v><i>inventer</i><t>aim:er</t></v>
	 <v><i>inviter</i><t>aim:er</t></v>
	 <v><i>jeter</i><t>j:eter</t></v>
	 <v><i>joindre</i><t>crai:ndre</t></v>
	 <v><i>jouer</i><t>aim:er</t></v>
	 <v><i>juger</i><t>man:ger</t></v>
	 <v><i>laisser</i><t>aim:er</t></v>
	 <v><i>lancer</i><t>pla:cer</t></v>
	 <v><i>lever</i><t>l:ever</t></v>
	 <v><i>lier</i><t>aim:er</t></v>
	 <v><i>lire</i><t>l:ire</t></v>
	 <v><i>lisser</i><t>aim:er</t></v>
	 <v><i>livrer</i><t>aim:er</t></v>
	 <v><i>lutter</i><t>aim:er</t></v>
	 <v><i>maintenir</i><t>t:enir</t></v>
	 <v><i>manger</i><t>man:ger</t></v>
	 <v><i>manquer</i><t>aim:er</t></v>
	 <v><i>marcher</i><t>aim:er</t></v>
	 <v><i>marier</i><t>aim:er</t></v>
	 <v><i>marquer</i><t>aim:er</t></v>
	 <v><i>mêler</i><t>aim:er</t></v>
	 <v><i>menacer</i><t>pla:cer</t></v>
	 <v><i>mener</i><t>m:ener</t></v>
	 <v><i>mentir</i><t>men:tir</t></v>
	 <v><i>mériter</i><t>aim:er</t></v>
	 <v><i>mettre</i><t>m:ettre</t></v>
	 <v><i>monter</i><t>aim:er</t></v>
	 <v><i>montrer</i><t>aim:er</t></v>
	 <v><i>mourir</i><t>m:ourir</t></v>
	 <v><i>naître</i><t>n:aître</t></v>
	 <v><i>nommer</i><t>aim:er</t></v>
	 <v><i>nourrir</i><t>fin:ir</t></v>
	 <v><i>noyer</i><t>netto:yer</t></v>
	 <v><i>obéir</i><t>fin:ir</t></v>
	 <v><i>obliger</i><t>man:ger</t></v>
	 <v><i>observer</i><t>aim:er</t></v>
	 <v><i>obtenir</i><t>t:enir</t></v>
	 <v><i>occuper</i><t>aim:er</t></v>
	 <v><i>offrir</i><t>ouv:rir</t></v>
	 <v><i>oser</i><t>aim:er</t></v>
	 <v><i>oublier</i><t>aim:er</t></v>
	 <v><i>ouvrir</i><t>ouv:rir</t></v>
	 <v><i>paraître</i><t>rep:aître</t></v>
	 <v><i>parcourir</i><t>cour:ir</t></v>
	 <v><i>parer</i><t>aim:er</t></v>
	 <v><i>parler</i><t>aim:er</t></v>
	 <v><i>partager</i><t>man:ger</t></v>
	 <v><i>partir</i><t>men:tir</t></v>
	 <v><i>parvenir</i><t>t:enir</t></v>
	 <v><i>passer</i><t>aim:er</t></v>
	 <v><i>payer</i><t>pa:yer</t></v>
	 <v><i>pencher</i><t>aim:er</t></v>
	 <v><i>pendre</i><t>ten:dre</t></v>
	 <v><i>pénétrer</i><t>imp:étrer</t></v>
	 <v><i>penser</i><t>aim:er</t></v>
	 <v><i>perdre</i><t>ten:dre</t></v>
	 <v><i>permettre</i><t>m:ettre</t></v>
	 <v><i>peser</i><t>p:eser</t></v>
	 <v><i>piquer</i><t>aim:er</t></v>
	 <v><i>placer</i><t>pla:cer</t></v>
	 <v><i>plaindre</i><t>crai:ndre</t></v>
	 <v><i>plaire</i><t>pl:aire</t></v>
	 <v><i>pleurer</i><t>aim:er</t></v>
	 <v><i>plier</i><t>aim:er</t></v>
	 <v><i>plonger</i><t>man:ger</t></v>
	 <v><i>porter</i><t>aim:er</t></v>
	 <v><i>poser</i><t>aim:er</t></v>
	 <v><i>posséder</i><t>c:éder</t></v>
	 <v><i>poursuivre</i><t>sui:vre</t></v>
	 <v><i>pousser</i><t>aim:er</t></v>
	 <v><i>pouvoir</i><t>p:ouvoir</t></v>
	 <v><i>précéder</i><t>c:éder</t></v>
	 <v><i>précipiter</i><t>aim:er</t></v>
	 <v><i>préférer</i><t>réf:érer</t></v>
	 <v><i>prendre</i><t>pr:endre</t></v>
	 <v><i>préparer</i><t>aim:er</t></v>
	 <v><i>présenter</i><t>aim:er</t></v>
	 <v><i>presser</i><t>aim:er</t></v>
	 <v><i>prétendre</i><t>ten:dre</t></v>
	 <v><i>prêter</i><t>aim:er</t></v>
	 <v><i>prévenir</i><t>t:enir</t></v>
	 <v><i>prévoir</i><t>prév:oir</t></v>
	 <v><i>prier</i><t>aim:er</t></v>
	 <v><i>produire</i><t>condui:re</t></v>
	 <v><i>profiter</i><t>aim:er</t></v>
	 <v><i>promener</i><t>m:ener</t></v>
	 <v><i>promettre</i><t>m:ettre</t></v>
	 <v><i>prononcer</i><t>pla:cer</t></v>
	 <v><i>proposer</i><t>aim:er</t></v>
	 <v><i>protéger</i><t>abr:éger</t></v>
	 <v><i>prouver</i><t>aim:er</t></v>
	 <v><i>quitter</i><t>aim:er</t></v>
	 <v><i>raconter</i><t>aim:er</t></v>
	 <v><i>ramasser</i><t>aim:er</t></v>
	 <v><i>ramener</i><t>m:ener</t></v>
	 <v><i>rappeler</i><t>app:eler</t></v>
	 <v><i>rapporter</i><t>aim:er</t></v>
	 <v><i>rassurer</i><t>aim:er</t></v>
	 <v><i>recevoir</i><t>dé:cevoir</t></v>
	 <v><i>réclamer</i><t>aim:er</t></v>
	 <v><i>recueillir</i><t>cueill:ir</t></v>
	 <v><i>reculer</i><t>aim:er</t></v>
	 <v><i>redevenir</i><t>t:enir</t></v>
	 <v><i>réduire</i><t>condui:re</t></v>
	 <v><i>réfléchir</i><t>fin:ir</t></v>
	 <v><i>refuser</i><t>aim:er</t></v>
	 <v><i>regarder</i><t>aim:er</t></v>
	 <v><i>regretter</i><t>aim:er</t></v>
	 <v><i>rejeter</i><t>j:eter</t></v>
	 <v><i>rejoindre</i><t>crai:ndre</t></v>
	 <v><i>relever</i><t>l:ever</t></v>
	 <v><i>remarquer</i><t>aim:er</t></v>
	 <v><i>remercier</i><t>aim:er</t></v>
	 <v><i>remettre</i><t>m:ettre</t></v>
	 <v><i>remonter</i><t>aim:er</t></v>
	 <v><i>remplacer</i><t>pla:cer</t></v>
	 <v><i>remplir</i><t>fin:ir</t></v>
	 <v><i>rencontrer</i><t>aim:er</t></v>
	 <v><i>rendre</i><t>ten:dre</t></v>
	 <v><i>renoncer</i><t>pla:cer</t></v>
	 <v><i>rentrer</i><t>aim:er</t></v>
	 <v><i>renverser</i><t>aim:er</t></v>
	 <v><i>répandre</i><t>ten:dre</t></v>
	 <v><i>répéter</i><t>décr:éter</t></v>
	 <v><i>répondre</i><t>ten:dre</t></v>
	 <v><i>reposer</i><t>aim:er</t></v>
	 <v><i>repousser</i><t>aim:er</t></v>
	 <v><i>reprendre</i><t>pr:endre</t></v>
	 <v><i>réserver</i><t>aim:er</t></v>
	 <v><i>résister</i><t>aim:er</t></v>
	 <v><i>résoudre</i><t>réso:udre</t></v>
	 <v><i>respecter</i><t>aim:er</t></v>
	 <v><i>respirer</i><t>aim:er</t></v>
	 <v><i>ressembler</i><t>aim:er</t></v>
	 <v><i>rester</i><t>aim:er</t></v>
	 <v><i>retenir</i><t>t:enir</t></v>
	 <v><i>retirer</i><t>aim:er</t></v>
	 <v><i>retomber</i><t>aim:er</t></v>
	 <v><i>retourner</i><t>aim:er</t></v>
	 <v><i>retrouver</i><t>aim:er</t></v>
	 <v><i>réunir</i><t>fin:ir</t></v>
	 <v><i>réussir</i><t>fin:ir</t></v>
	 <v><i>réveiller</i><t>aim:er</t></v>
	 <v><i>révéler</i><t>rév:éler</t></v>
	 <v><i>revenir</i><t>t:enir</t></v>
	 <v><i>rêver</i><t>aim:er</t></v>
	 <v><i>revoir</i><t>v:oir</t></v>
	 <v><i>rire</i><t>r:ire</t></v>
	 <v><i>risquer</i><t>aim:er</t></v>
	 <v><i>rompre</i><t>rom:pre</t></v>
	 <v><i>rouler</i><t>aim:er</t></v>
	 <v><i>saisir</i><t>fin:ir</t></v>
	 <v><i>saluer</i><t>aim:er</t></v>
	 <v><i>satisfaire</i><t>f:aire</t></v>
	 <v><i>sauter</i><t>aim:er</t></v>
	 <v><i>sauver</i><t>aim:er</t></v>
	 <v><i>savoir</i><t>s:avoir</t></v>
	 <v><i>sembler</i><t>aim:er</t></v>
	 <v><i>semer</i><t>s:emer</t></v>
	 <v><i>sentir</i><t>men:tir</t></v>
	 <v><i>séparer</i><t>aim:er</t></v>
	 <v><i>serrer</i><t>aim:er</t></v>
	 <v><i>servir</i><t>ser:vir</t></v>
	 <v><i>signer</i><t>aim:er</t></v>
	 <v><i>signifier</i><t>aim:er</t></v>
	 <v><i>songer</i><t>man:ger</t></v>
	 <v><i>sonner</i><t>aim:er</t></v>
	 <v><i>sortir</i><t>men:tir</t></v>
	 <v><i>souffler</i><t>aim:er</t></v>
	 <v><i>souffrir</i><t>ouv:rir</t></v>
	 <v><i>souhaiter</i><t>aim:er</t></v>
	 <v><i>soulever</i><t>l:ever</t></v>
	 <v><i>soumettre</i><t>m:ettre</t></v>
	 <v><i>sourire</i><t>r:ire</t></v>
	 <v><i>soutenir</i><t>t:enir</t></v>
	 <v><i>souvenir</i><t>t:enir</t></v>
	 <v><i>subir</i><t>fin:ir</t></v>
	 <v><i>suffire</i><t>suff:ire</t></v>
	 <v><i>suivre</i><t>sui:vre</t></v>
	 <v><i>supporter</i><t>aim:er</t></v>
	 <v><i>supposer</i><t>aim:er</t></v>
	 <v><i>surprendre</i><t>pr:endre</t></v>
	 <v><i>surveiller</i><t>aim:er</t></v>
	 <v><i>taire</i><t>t:aire</t></v>
	 <v><i>tendre</i><t>ten:dre</t></v>
	 <v><i>tenir</i><t>t:enir</t></v>
	 <v><i>tenter</i><t>aim:er</t></v>
	 <v><i>terminer</i><t>aim:er</t></v>
	 <v><i>tirer</i><t>aim:er</t></v>
	 <v><i>tomber</i><t>aim:er</t></v>
	 <v><i>toucher</i><t>aim:er</t></v>
	 <v><i>tourner</i><t>aim:er</t></v>
	 <v><i>tracer</i><t>pla:cer</t></v>
	 <v><i>traîner</i><t>aim:er</t></v>
	 <v><i>traiter</i><t>aim:er</t></v>
	 <v><i>travailler</i><t>aim:er</t></v>
	 <v><i>traverser</i><t>aim:er</t></v>
	 <v><i>trembler</i><t>aim:er</t></v>
	 <v><i>tromper</i><t>aim:er</t></v>
	 <v><i>troubler</i><t>aim:er</t></v>
	 <v><i>trouver</i><t>aim:er</t></v>
	 <v><i>tuer</i><t>aim:er</t></v>
	 <v><i>user</i><t>aim:er</t></v>
	 <v><i>vaincre</i><t>vain:cre</t></v>
	 <v><i>valoir</i><t>va:loir</t></v>
	 <v><i>veiller</i><t>aim:er</t></v>
	 <v><i>vendre</i><t>ten:dre</t></v>
	 <v><i>venir</i><t>t:enir</t></v>
	 <v><i>verser</i><t>aim:er</t></v>
	 <v><i>vêtir</i><t>vêt:ir</t></v>
	 <v><i>visiter</i><t>aim:er</t></v>
	 <v><i>vivre</i><t>v:ivre</t></v>
	 <v><i>voir</i><t>v:oir</t></v>
	 <v><i>voler</i><t>aim:er</t></v>
	 <v><i>vouloir</i><t>v:ouloir</t></v>
	 <v><i>voyager</i><t>man:ger</t></v>

</verbs-fr>
